spring:
  devtools:
    livereload:
      enabled: false
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todo
    username: todo
    password: koscom

#spring:
#  data:
#    rest:
#      return-body-on-create: false
#      return-body-on-update: false
#      base-path: /api

#      default-page-size: 10

#spring:
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: default

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/todo"
    username: todo
    password: koscom